/* Spec 025 — TEACHER LIBRARY (sara's teaching resources). A display-only shelf of
 * the authored teaching materials (TEACHER_PREVIEW.materials tm1/tm2/tm3): each card
 * carries the file type icon, an authored type chip, an authored publish-status chip,
 * and the authored linked-course label. Adding a new resource and pulling one down are
 * both honest backendRequired gates (no fake upload/download/open/delete/cloud-sync).
 * A client-side search (the shared data-filter/facet mechanism, evidenced by the
 * reference search_form) filters the three authored cards by title/type — no backend.
 * Display-only; NO computed values; ZERO figure-bearing/flagged vocabulary anywhere
 * (copy AND comments — the standing teacher hard rule); zero body anchors. */
import { t } from '../i18n.js';
import { icon } from '../icons.js';
import { esc, facetAttrs } from '../dom.js';
import { pageHead, secHead, gateNote } from '../components/portal-page.js';
import { chip } from '../components/ui.js';
import { filterBar } from '../components/filter-bar.js';
import { noResults } from '../components/states.js';
import { TEACHER_PREVIEW } from '../fixtures/portal.js';

/* authored type label per file-type icon (display-only classification, no scale) */
const TYPE_KEY_BY_ICON = {
  'file-text': 'prt.tch.pg.library.typeDoc',
  play: 'prt.tch.pg.library.typeVideo',
  materials: 'prt.tch.pg.library.typeSlides',
};

/* client-side search facets over the authored cards (shared data-filter mechanism) */
const searchFacets = (m, typeKey) => facetAttrs({ search: `${t(m.titleKey)} ${t(typeKey)}` });

function resourceCard(m) {
  const typeKey = TYPE_KEY_BY_ICON[m.typeIcon] || 'prt.tch.pg.library.typeDoc';
  return `<div class="pt-card" ${searchFacets(m, typeKey)}>
    <div class="pt-card-row">
      <span class="pt-time">${icon(m.typeIcon, 'ico')}</span>
      <div style="flex:1;min-width:0">
        <div class="pt-card-title">${esc(t(m.titleKey))}</div>
        <div class="pt-card-sub">${esc(t('prt.tch.pg.library.course1'))}</div>
      </div>
      ${chip({ labelKey: 'prt.tch.pg.library.statusPublished', tone: 'completed', icon: 'check-circle' })}
    </div>
    <div class="pt-tags">
      ${chip({ labelKey: typeKey, tone: 'neutral', icon: m.typeIcon })}
    </div>
  </div>`;
}

export function renderTeacherLibrary() {
  /* Spec 045 — T033 lead correction: `filterBar()` and `noResults()` emit a few lines that end in
   * spaces. Every page already using them carries that whitespace in its committed bytes, so it is
   * pre-existing component output rather than anything this page introduced — but on THIS page those
   * lines are newly added, which makes `git diff --check` (a required Spec-045 gate) fail on them.
   * The fix is contained here rather than in the shared components: trimming `filter-bar.js` /
   * `states.js` would rewrite the generated bytes of every other page that uses them, which is
   * exactly the unrelated drift the impact contract forbids. Trailing whitespace is stripped only
   * from this page's own composed markup; no visible output changes. */
  return `
    ${pageHead('prt.tch.pg.library.title', 'prt.tch.pg.library.sub')}

    <section class="pt-section td-focus">
      ${secHead('materials', 'prt.tch.pg.library.title', 'prt.tch.pg.library.resHint')}
      ${filterBar({ targetId: 'library-resources', searchKey: 'prt.tch.pg.library.searchPh' })}
      <div id="library-resources" class="pt-cards">${TEACHER_PREVIEW.materials.map(resourceCard).join('')}</div>
      ${noResults()}
    </section>

    <div class="td-gates">
      ${gateNote('prt.tch.pg.library.uploadGate')}
      ${gateNote('prt.tch.pg.library.downloadGate')}
    </div>

    <div class="pt-note">${icon('help', 'ico ico-sm')}<span><strong>${esc(t('prt.tch.noteT'))}</strong> — ${esc(t('prt.band.noteTch'))}</span></div>
  `.replace(/[ \t]+$/gm, '');
}
